# Read the documentation: https://github.com/hautelook/AliceBundle/blob/v1.4.1/README.md
#hautelook_alice:
fidry_alice_data_fixtures:
    db_drivers:
        doctrine_orm: ~
#    locale: en_US
#    seed: 1
#    persist_once: false
#    loading_limit: 5


hautelook_alice:
  fixtures_path: 'DataFixtures/ORM'